name = "healthai-platform"
compatibility_date = "2024-09-02"

# Production Environment
[env.production]
name = "healthai-platform"
route = { pattern = "analysemyhealth.com/*", zone_name = "analysemyhealth.com" }

# Development Environment  
[env.development]
name = "healthai-platform-dev"
route = { pattern = "dev.analysemyhealth.com/*", zone_name = "analysemyhealth.com" }

# Enable Workers AI for both environments
[ai]
binding = "AI"

# Production R2 Storage
[[r2_buckets]]
binding = "DOCUMENTS"
bucket_name = "healthai-documents"

# Development R2 Storage
[env.development.r2_buckets]
binding = "DOCUMENTS" 
bucket_name = "healthai-documents-dev"

# Production D1 Database
[[d1_databases]]
binding = "DB"
database_name = "healthai-sessions"
database_id = "1fb0a82f-75ed-475f-b206-bb46dd6940e8"

# Development D1 Database
[env.development.d1_databases]
binding = "DB"
database_name = "healthai-sessions-dev"
database_id = "69c4310a-867e-40f1-b0cd-9fbf09f9eea6"
